const foods = [
    {
        "id": 1,
        "name": 'Healthy meal plan',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/urYRDHM.png',
        "price": 23.99,
        "cetagory": 'lunch',
    },
    {
        "id": 2,
        "name": 'Fried Chicken Bento',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/E8TWqn7.png',
        "price": 9.99,
        "cetagory": 'lunch',
    },
    {
        "id": 3,
        "name": 'Tarragon-Rubbed-Salmon',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/zoLBKT3.png',
        "price": 6.99,
        "cetagory": 'lunch',
    },
    {
        "id": 4,
        "name": 'Indian Lunch',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/Z3S9sVY.png',
        "price": 8.99,
        "cetagory": 'lunch',
    },
    {
        "id": 5,
        "name": 'Beef Steak',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/zsNDRNj.png',
        "price": 5.99,
        "cetagory": 'lunch',
    },
    {
        "id": 6,
        "name": 'Honey soy glazed salmon with peppers',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/QGTpeFr.png',
        "price": 7.99,
        "cetagory": 'lunch',
    },
    {
        "id": 7,
        "name": 'Bagel and cream cheese',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/JOcOW33.png',
        "price": 6.99,
        "cetagory": 'breakfast',
    },
    {
        "id": 8,
        "name": 'Breakfast sandwich',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/meb8IkS.png',
        "price": 23.99,
        "cetagory": 'breakfast',
    },
    {
        "id": 9,
        "name": 'Baked Ciken',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/AwS9K3M.png',
        "price": 9.99,
        "cetagory": 'breakfast',
    },
    {
        "id": 10,
        "name": 'Eggs Benedict',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/svafo7I.png',
        "price": 8.99,
        "cetagory": 'breakfast',
    },
    {
        "id": 11,
        "name": 'Toast Croissant Fried Egg',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/CvVPYii.png',
        "price": 19.99,
        "cetagory": 'breakfast',
    },
    {
        "id": 12,
        "name": 'Full Breakfast Fried Egg Toast Brunch',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/EwIctFt.png',
        "price": 3.99,
        "cetagory": 'breakfast',
    },
    {
        "id": 13,
        "name": 'Salmon With Grapefruit and Lentil Salad',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/nk3YpI5.png',
        "price": 9.99,
        "cetagory": 'dinner',
    },
    {
        "id": 14,
        "name": 'Lemony Salmon Piccata',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/A4tdDVX.png',
        "price": 10.99,
        "cetagory": 'dinner',
    },
    {
        "id": 15,
        "name": 'Pork Tenderloin With Quinoa Pilaf',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/Yf5Mcxz.png',
        "price": 12.99,
        "cetagory": 'dinner',
    },
    {
        "id": 16,
        "name": 'Freanch fries with cheese',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/lsU4b6d.png',
        "price": 8.99,
        "cetagory": 'dinner',
    },
    {
        "id": 17,
        "name": 'Garlic butter Baked',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/2bOhmtv.png',
        "price": 19.99,
        "cetagory": 'dinner',
    },
    {
        "id": 18,
        "name": 'Baked Chiken',
        "description": 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sunt, qui.',
        "image": 'https://i.imgur.com/I7JYGUj.png',
        "price": 3.99,
        "cetagory": 'dinner',
    }

]
export default foods;